import { Copy, Download, Printer } from 'lucide-react';
import StatBar from './StatBar';

export default function DocumentEditor({ value, onChange, onCopy, onDownload, onPrint, loading }) {
  return <section className="card flex min-h-[560px] flex-col overflow-hidden" aria-label="Generated D.O. Letter">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-slate-50 px-5 py-4 dark:border-slate-700 dark:bg-slate-800/60"><div><h2 className="font-semibold text-government-900 dark:text-white">Generated D.O. Letter</h2><p className="text-xs text-slate-500 dark:text-slate-400">Review and edit before sharing</p></div><div className="flex gap-1"><Action icon={<Copy size={16}/>} label="Copy" onClick={onCopy} disabled={!value}/><Action icon={<Download size={16}/>} label="DOCX" onClick={onDownload} disabled={!value}/><Action icon={<Printer size={16}/>} label="Print" onClick={onPrint} disabled={!value}/></div></div>
    <div className="relative flex-1 bg-slate-100 p-4 sm:p-7 dark:bg-slate-950"><div className="paper mx-auto min-h-[430px] max-w-[700px]"><textarea value={value} onChange={e => onChange(e.target.value)} aria-label="Generated D.O. Letter text" placeholder="Your polished Demi-Official Letter will appear here…" className="h-full min-h-[400px] w-full resize-none bg-transparent font-serif text-[15px] leading-7 text-slate-800 outline-none placeholder:text-slate-400 dark:text-slate-100" />{loading && <div className="absolute inset-0 grid place-items-center bg-white/75 backdrop-blur-[1px] dark:bg-slate-900/75"><div className="text-center"><span className="spinner mx-auto mb-3"/><p className="font-medium text-government-800 dark:text-government-100">Preparing your D.O. letter…</p><p className="mt-1 text-sm text-slate-500">This usually takes a few seconds.</p></div></div>}</div></div><div className="border-t border-slate-100 px-5 py-3 dark:border-slate-700"><StatBar text={value}/></div>
  </section>;
}
function Action({ icon, label, onClick, disabled }) { return <button type="button" onClick={onClick} disabled={disabled} className="icon-button" aria-label={label}>{icon}<span className="hidden sm:inline">{label}</span></button>; }

